### ISSUE TITLE
Error on Windows Server 2016

### ISSUE THREAD

**Issue by dvanboven** [theangryangel/prtg-addons#2]
Currently I'm using this PowerShell script within our PRTG setup.

It's working fine on our "Windows Server 2008 R2" servers. But when I execute it towards our "Windows Server 2016", it gives the following error:

```
Write-Debug : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
At C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\Get-DFSRBacklog.ps1:245 char:37
+                         write-debug $BacklogCount
+                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-Debug], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.WriteDebugCommand
```

Do you know how to fix this error?
Thanks in advance.

Kind Regards!

**Comment by theangryangel** [comment]
I am out of the country and unable to look at this for at least 2 weeks. I can tell you the backlog count is getting set to something it probably shouldn’t but until I get to a computer it’s difficult for me to tell you more.

**Comment by dvanboven** [comment]
Alright, not a problem. Keep me posted.

**Comment by theangryangel** [comment]
With thanks to @Juzzle1 for 2 fixes here :) Nice one dude :+1:
